### ISSUE TITLE
Deserialization

### ISSUE THREAD

**Issue by akubisch** [dfdx/Kafka.jl#11]
Hi again,

while trying to start to work with Kafka and Julia, I've discovered that the serialization of objects for producers according to the examples is done like:
```
# produce new messages
# each message is a key-value pair where both key and value are byte arrays
keys = [convert(Vector{UInt8}, key) for key in ["1", "2", "3"]]
values = [convert(Vector{UInt8}, value) for value in ["feel", "good", "inc."]]
messages = collect(zip(keys, values))
```
Is there a more convenient way of deserializing the result instead of subsetting the resulting tuples multiple times until I reach the UInt8 array? Maybe I am not familiar enough with Julia yet, but what would in above example be the easiest way from fetching `messages` to get to `["1","2","3"]` and `["feel", "good", "inc."]`?

Thanks again!

**Comment by dfdx** [comment]
This example is a bit too technical and low-level, let me provide another one:

```
# let's say, we have some data as a list of key-value pairs, where keys are e.g. IDs 
# and values are, say, text from chat room
data = [("1234", "hey, how are you? "), ("1235", "i'm fine, thanks. do you go to the party"),...]

# internally Kafka works only with byte arrays for keys and values, so we need to serialize
# our messages somehow. in practice people use ProtoBuf, Avro or whatever
# for this example we can simply use Julia's `convert` method
to_bytes(x) = convert(Vector{UInt8}, x)
messages = [(to_bytes(key), to_bytes(value)) for (key, value) in data]

# now we are ready to send these data. we will use topic "test", partition 0 
# `take!` is used to ensure that `produce` completed before we go to see the results
# in practice you don't need to wait, just produce as much data as you can
offset = take!(produce(kc, "test", 0, messages))

# read the messages back. here we assume that the topic was empty before the experiment
# so start_offset is 0. alternatively you can run `take!(latest_offset(kc, "test", 0))` to check 
# the current latest offset and substract a number of messages you want to read  
start_offset = 0
offset_messages = take!(fetch(kc, "test", 0, start_offset))

# on the receiver side you deserialize data accordingly 
```
Note that Kafka.jl currently doesn't manage offsets, so you need to either handle them yourself, use additional service (e.g. ZooKeeper as it was done in earlier versions of Kafka) or implement broker-side offset management (which appeared much later, so isn't present in Kafka.jl yet).

**Comment by akubisch** [comment]
Alright, thanks again, I have now created a lightweight and fully functional example myself in Julia 0.6.2. This really is fun - thanks for your great work and responsiveness!
